//file:noinspection GroovyAssignabilityCheck
//file:noinspection GroovyAccessibility
//file:noinspection GradlePackageVersionRange
plugins {
	id "fabric-loom" version "1.7-SNAPSHOT"
	id "maven-publish"
	id "me.modmuss50.mod-publish-plugin" version "0.3.5"
	id "idea"
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = project.archives_base_name
group = project.maven_group
version = mod_version

repositories {
	maven { url = "https://maven.shedaniel.me/" }
	maven { url = "https://maven.blamejared.com/" }
	maven { url = "https://maven.parchmentmc.org" }
	maven { url = "https://maven.quiltmc.org/repository/release" }
	maven { url = "https://api.modrinth.com/maven" }
	maven { url = "https://maven.terraformersmc.com/releases/" }
	maven { url = "https://mvn.devos.one/snapshots/" }
	maven { url = "https://mvn.devos.one/releases/" }
	maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
	maven { url = "https://maven.jamieswhiteshirt.com/libs-release" }
	maven { url = "https://jitpack.io/" }
	maven { url = "https://maven.dragons.plus/releases" }
	maven { url = "https://maven.dragons.plus/snapshots" }
	maven { url = "https://maven.createmod.net" }
	mavenLocal()
}

loom {
	accessWidenerPath = file("src/main/resources/create_enchantment_industry.accesswidener")

	sourceSets {
		main {
			resources {
				srcDir("src/generated/resources")
				exclude("src/generated/resources/.cache")
			}
		}
	}

	runs {
		datagen {
			client()
			name "Data Generation"
			vmArg "-Dfabric-api.datagen"
			vmArg "-Dfabric-api.datagen.output-dir=${file("src/generated/resources")}"
			vmArg "-Dfabric-api.datagen.modid=create_enchantment_industry"
			vmArg "-Dporting_lib.datagen.existing_resources=${file("src/main/resources")}"
		}

		server {
			runDir "run/server"
		}
	}
}

dependencies {
	// Minecraft + mappings (YARN + PARCHMENT)
	minecraft("com.mojang:minecraft:${minecraft_version}")

	mappings(loom.layered {
		it.officialMojangMappings { nameSyntheticMembers = false }
		it.parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
	})

	modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
	modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_api_version}")

	// Create Fabric 6
	modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }

	modImplementation("dev.engine-room.flywheel:flywheel-fabric-${minecraft_version}:${flywheel_version}")

	// Porting Lib (required by Create Fabric)
	modImplementation(include("io.github.fabricators_of_create.Porting-Lib:data:${project.porting_lib_version}"))
	modImplementation(include("io.github.fabricators_of_create.Porting-Lib:transfer:${project.porting_lib_version}"))
	modImplementation(include("io.github.fabricators_of_create.Porting-Lib:fluids:${project.porting_lib_version}"))
	modImplementation(include("io.github.fabricators_of_create.Porting-Lib:base:${project.porting_lib_version}"))

	// Dragon Lib
	include(modImplementation("plus.dragons.createdragonlib:create_dragon_lib-fabric-${minecraft_version}:${dragonlib_version}") {
		transitive = false
	})

	// Dev QOL
	modLocalRuntime("maven.modrinth:lazydfu:${lazydfu_version}")
	modLocalRuntime("com.terraformersmc:modmenu:${modmenu_version}")

	// Recipe viewers
	switch (recipe_viewer.toLowerCase(Locale.ROOT)) {
		case "jei": modLocalRuntime("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"); break
		case "rei": modLocalRuntime("me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"); break
		case "emi": modLocalRuntime("dev.emi:emi:${emi_version}"); break
		case "disabled": break
		default: println("Unknown recipe viewer: ${recipe_viewer}")
	}

	modCompileOnly("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")
	modCompileOnly("mezz.jei:jei-${minecraft_version}-common:${jei_version}")
}

processResources {
	Map<String, String> properties = new HashMap<>()
	properties.put("version", version)
	properties.put("fabric_loader_version", fabric_loader_version)
	properties.put("fabric_api_version", fabric_api_version)
	properties.put("create_version", create_version)
	properties.put("minecraft_version", minecraft_version)

	properties.forEach { k, v -> inputs.property(k, v) }

	filesMatching("fabric.mod.json") {
		expand properties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${archivesBaseName}" }
	}
}

publishMods {
	file = remapJar.archiveFile
	changelog = new File("changelog/${mod_version}.md").text
	version = mod_version
	type = STABLE
	displayName = "CEI ${mod_version} for Create ${minecraft_version}-${create_version}"
	modLoaders.add("fabric")
	modLoaders.add("quilt")

	curseforge {
		projectId = "876129"
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		minecraftVersions.add(minecraft_version)
		requires { slug = "create-fabric"; slug = "fabric-api" }
	}

	modrinth {
		projectId = "AEZO385x"
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		minecraftVersions.add(minecraft_version)
		requires { slug = "create-fabric"; slug = "fabric-api" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
